### ISSUE TITLE
An error for data loading

### ISSUE THREAD

**Issue by strive789** [lxa9867/ControlVAR#19]
Traceback (most recent call last):
  File "/data/ControlVAR/train_control_var.py", line 25, in <module>
    from datasets import create_dataset
  File "/data/ControlVAR/datasets/__init__.py", line 1, in <module>
    from .build import create_dataset
  File "/data/ControlVAR/datasets/build.py", line 6, in <module>
    from .imagenetS import ImagenetSDataset
  File "/data/ControlVAR/datasets/imagenetS.py", line 9, in <module>
    from .utils import semantic_to_instance_map
  File "/data/ControlVAR/datasets/utils.py", line 5, in <module>
    import torchdata.datapipes as dps
  File "/data/anaconda3/envs/cvar/lib/python3.10/site-packages/torchdata/datapipes/__init__.py", line 9, in <module>
    from torchdata import _extension  # noqa: F401
  File "/data/anaconda3/envs/cvar/lib/python3.10/site-packages/torchdata/__init__.py", line 29, in __getattr__
    return importlib.import_module("." + name, __name__)
  File "/data/anaconda3/envs/cvar/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data/anaconda3/envs/cvar/lib/python3.10/site-packages/torchdata/_extension.py", line 34, in <module>
    _init_extension()
  File "/data/anaconda3/envs/cvar/lib/python3.10/site-packages/torchdata/_extension.py", line 31, in _init_extension
    from torchdata import _torchdata as _torchdata
  File "/data/anaconda3/envs/cvar/lib/python3.10/site-packages/torchdata/__init__.py", line 29, in __getattr__
    return importlib.import_module("." + name, __name__)
  File "/data/anaconda3/envs/cvar/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0

-----------------------------------------------------------------------------------------------------------------------------------------------

I encountered this error during data loading and tried several methods to fix it, but none have worked. Has anyone experienced the same issue?

**Comment by strive789** [comment]
Commenting out ‘’import torchdata.datapipes as dps‘’ in ‘’utils.py‘’ temporarily resolves the issue.
